version: '3.8'

services:
  vite-react:
    build:
      context: ./vite-react
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./vite-react:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development