services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - ./mongo-data:/data/db
    command: mongod

  flask:
    build: ./flask
    env_file:
      - ./flask/.env
    container_name: flask
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:examplepassword@mongodb:27017/?authSource=admin
      MONGO_DB_NAME: mydatabase
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}
      PLATFORM_OPENAI_KEY: ${PLATFORM_OPENAI_KEY}
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5002:5002"
    command: gunicorn --bind 0.0.0.0:5002 main:app

  vite-react:
    build:
      context: ./vite-react
      dockerfile: Dockerfile
    container_name: vite-react
    ports:
      - "80:80"

volumes:
  mongo_data:
