services:
  vite-react:
    build:
      context: ./vite-react
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./vite-react:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=flask.main
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONPATH=/app/flask
    volumes:
      - ./:/app
    ports:
      - "5002:5002"
    command: flask run --host=0.0.0.0 --port=5002 --reload
