import { useState, useEffect } from "react";
import { useAppContext } from "@/context/useAppContext";
import { useNavigate } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { CheckCircle } from "lucide-react";
import { TextInputDialog } from "@/components/TextInputDialog";

export function WelcomeInputView() {
  const navigate = useNavigate();
  const { letterLabData } = useAppContext();

  useEffect(() => {
    if (!letterLabData?.hasAccess) {
      navigate("/enter");
    }
  }, [letterLabData, navigate]);

  const {
    resumeText,
    jobDescription,
    setResumeText,
    setJobDescription,
    setLetterLabData,
  } = useAppContext();

  const [showResumePopup, setShowResumePopup] = useState(false);
  const [showJobPopup, setShowJobPopup] = useState(false);

  const handleGenerate = async () => {
    if (!resumeText || !jobDescription) {
      alert("Please provide both a resume and a job description.");
      return;
    }

    // Store resume and job description, let backend create session
    setLetterLabData(prev => ({
      ...prev,
      resume: resumeText,
      job_desc: jobDescription,
      document_id: undefined // No temporary ID - let backend create real session
    }));
    
    navigate("/control-profile");
  };

  return (
    <Card className="w-full max-w-2xl p-6 text-center shadow-lg bg-white space-y-6">
      <CardHeader>
        <CardTitle className="text-2xl font-bold">
          Welcome to LL.me: Collaborative Alignment Tool
        </CardTitle>
      </CardHeader>

      <CardContent className="bg-blue-100/70 p-4 rounded-lg border border-blue-200 space-y-4 text-left text-gray-700 leading-relaxed">
        <p>
          <strong>Thank you for participating in this study!</strong> This tool is designed to explore how you and AI can work together to create a personal profile statement that truly reflects your identity, values, and priorities.
        </p>
        <p>
          📄 To start, you'll paste in your <strong>resume</strong> and a{" "}
          <strong>job description</strong>.
        </p>
        <p>
          🧠 Then, you'll read a short profile statement generated by the tool, rate how well it reflects you, and provide feedback on it.
        </p>
        <p>
          ✍️ After that, you'll collaborate with the tool to refine and create a new profile statement that better aligns with your goals and self-understanding.
        </p>
        <p>
          ⬇️ Upload your <strong>resume</strong> and the{" "}
          <strong>job you're applying for</strong> to get started!
        </p>
      </CardContent>

      <CardContent className="space-y-4">
        <div className="flex flex-col gap-4">
          <Button
            variant="outline"
            className={
              resumeText
                ? "border-2 border-green-500 hover:border-green-600"
                : !resumeText && !jobDescription
                ? "border-2 border-orange-500 hover:border-orange-600"
                : ""
            }
            onClick={() => setShowResumePopup(true)}
          >
            {resumeText && (
              <CheckCircle className="w-5 h-5 text-green-600 mr-2" />
            )}
            Paste Your Resume
          </Button>
          <Button
            variant="outline"
            className={
              jobDescription
                ? "border-2 border-green-500 hover:border-green-600"
                : resumeText && !jobDescription
                ? "border-2 border-orange-500 hover:border-orange-600"
                : ""
            }
            onClick={() => setShowJobPopup(true)}
          >
            {jobDescription && (
              <CheckCircle className="w-5 h-5 text-green-600 mr-2" />
            )}
            Paste Job Description
          </Button>
          <Button
            variant="outline"
            className={
              resumeText && jobDescription
                ? "border-2 border-orange-500 hover:border-orange-600"
                : ""
            }
            onClick={handleGenerate}
            disabled={!resumeText || !jobDescription}
          >
            Generate Profile Statement
          </Button>
        </div>
      </CardContent>

      {/* Resume Dialog */}
      <TextInputDialog
        open={showResumePopup}
        title="Your Resume"
        description="Paste your resume text below."
        initialValue=""
        onSave={setResumeText}
        onClose={() => setShowResumePopup(false)}
      />

      {/* Job Description Dialog */}
      <TextInputDialog
        open={showJobPopup}
        title="Job Description"
        description="Paste the job description text below."
        initialValue=""
        onSave={setJobDescription}
        onClose={() => setShowJobPopup(false)}
      />
    </Card>
  );
}